#!/usr/bin/perl
#
# reconnect adsl if its fscked
#
#

die "adsl-reconnect [checking interval]\n" unless $ARGV[0];

exit if fork();


while (1) {
$file = system 'ls /var/run/ppp?.pid';

if ($file) {
    print "file does not exists";
    system "killall -w pppd";
    system "pon dsl-provider";
}

sleep $ARGV[0];
}
