#!/usr/bin/perl
#
#
#
# generates local.domains file out of httpd.conf , note that you can use 
# wild cards which is normal in debian installation (/etc/apache/conf.d/).
#
#
#

use warnings;
use strict;

my @httpd;
my $count=0;
my $temp;

while () {
my $isnew=0;

open (OFILE,">httpd.conf.new") or die;
open (FILE,'/usr/local/apache/conf/httpd.conf') or die;


    @httpd=<FILE>;
    foreach my $line (@httpd) {

	if ($httpd[$count] =~ /^DocumentRoot/) {
	    	if ($httpd[$count+1] !~ /^php_admin/) {
	    	if ($httpd[$count+1] !~ /</) {

	print OFILE $line;

	$line =~ s/DocumentRoot/php_admin_value open_basedir/;
	$line =~ s/public_html.*/:\/tmp/;
	$isnew=1;
    }}};

	print OFILE $line;
	$count++;
    };

	    close FILE;
	    close OFILE;
if ($isnew=1) {
system "mv httpd.conf.new /usr/local/apache/conf/httpd.conf";
system "service httpd restart";
}

sleep 200;
}
