#!/usr/bin/perl
#
#
#
# this script does look for DocumentRoot directive in virtualhosts 
# and add php_admin_value open_basedir restricted to home that 
# directory and /tmp , its highly recomended for hosting 
# envinronments 
#
#
#

use warnings;
use strict;


exit if fork();
while () {
my @httpd;
my $count=0;
my $temp;


my $isnew=0;

open (OFILE,">httpd.conf.new") or die;
open (FILE,'/usr/local/apache/conf/httpd.conf') or die;


    @httpd=<FILE>;
    foreach my $line (@httpd) {

	if ($httpd[$count] =~ /DocumentRoot/ig) {
	    	if ($httpd[$count+1] !~ /basedir/ig) {


	print OFILE $line;

	$line =~ s/DocumentRoot/php_admin_value open_basedir/;
	$line =~ s/public_html.*/:\/tmp/;
	$isnew=1;
    }};
	print OFILE $line;
	$count++;
    };

	    close FILE;
	    close OFILE;
if ($isnew==1) {
system "mv httpd.conf.new /usr/local/apache/conf/httpd.conf";
system "/etc/init.d/httpd restart";
}

sleep 20;
}
