#!/bin/sh
#
#
#
# powersave , power save script 
#
#
#

function save {
    echo "powersave" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
    echo "1" > "/proc/sys/vm/laptop_mode"
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state
    exit
}
function free {
    echo "0" > "/proc/sys/vm/laptop_mode"
    echo "performance" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state
    exit
}
function ondemand {
    echo "1" > "/proc/sys/vm/laptop_mode"
    echo "ondemand" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state
    exit
}

function conservative {
    echo "1" > "/proc/sys/vm/laptop_mode"
    echo "conservative" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state
    exit
}

function userspace {
    echo "userspace" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state
    exit
}
function show {
    echo "Laptop mode :" `cat /proc/sys/vm/laptop_mode`
    echo "Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
    echo "Available Scaling Governor :" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors`
    cat /proc/acpi/thermal_zone/THRM/temperature
    cat /proc/acpi/ac_adapter/ACAD/state
    cat /proc/acpi/battery/BAT1/state

    exit
}
if [ -x $1 ]; then show
fi  
if [ $1 = "save" ]; then save
fi
if [ $1 = "free" ]; then free
fi
if [ $1 = "show" ]; then show
fi  
if [ $1 = "ondemand" ]; then ondemand
fi
if [ $1 = "userspace" ]; then userspace
fi
if [ $1 = "conservative" ]; then conservative
fi
