.TH man 1 "31 March 2007" "0.1" "find_sgidsuid man page"
.SH NAME
find_sgidsuid
.SH SYNOPSIS
.B this script tries to find set uid/gid files
.SH EXAMPLES
find_sgidsuid /usr/
.SH DESCRIPTION
This script tries to find set uid/gid files on entire give path , its recursive .
.SH OPTIONS
find_sgidsuid <path>
.SH FILES
.P 
.I /usr/share/man/man1/find_sgidsuid.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
