.TH man 1 "31 March 2007" "0.1" "maildir2mbox man page"
.SH NAME
maildir2mbox
.SH SYNOPSIS
.B this script converts maildir directories into mbox file .
.SH EXAMPLES
maildir2mbox /home/mail/
.SH DESCRIPTION
this script does convert maildir mail directories in mbox format file , file is created with 'mbox' name in current working directory .
.SH OPTIONS
maildir2mbox <path>
.SH FILES
.P 
.I /usr/share/man/man1/maildir2mbox.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
