.TH man 1 "31 March 2007" "0.1" "packup man page"
.SH NAME
packup
.SH SYNOPSIS
.B Packup is backup archiver script .
.SH EXAMPLES
packup /home/*
.SH DESCRIPTION
this script does tar.gz any directory that is in given path , create /var/backups/backup/<date> directory and move all packed files there .
.SH OPTIONS
packup <path>
.SH FILES
.P 
.I /usr/share/man/man1/packup.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
