.TH man 1 "31 March 2007" "0.1" "pgen man page"
.SH NAME
pgen
.SH SYNOPSIS
.B Pgen is random and powerful password generator
.SH EXAMPLES
pgen
.SH FILES
.P 
.I /usr/share/man/man1/pgen.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
