.TH man 1 "31 March 2007" "0.1" "powersave man page"
.SH NAME
powersave
.SH SYNOPSIS
.B Powersave does change CPU Frequencies and laptop mode status .
.SH EXAMPLES
powersave save
.SH DESCRIPTION
this is useful on supported platforms ( mainly laptops machines ) , this is not an application , it just make doing this faster and easier . 
.SH OPTIONS
powersave <save> <free> <ondemand> <conservative> <userspace> <show>
.SH FILES
.P 
.I /usr/share/man/man1/powersave.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
