.TH man 1 "31 March 2007" "0.1" "space_remover man page"
.SH NAME
space_remover
.SH SYNOPSIS
.B remove spaces out of file names , replacing by _
.SH EXAMPLES
space_remover /home/*
.SH DESCRIPTION
this scripts looks for windows file names with space , replacer spaces with _.
.nf
for example "My documents" will get converted info "My_Documents".
.SH OPTIONS
space_remover <path>
.SH FILES
.P 
.I /usr/share/man/man1/space_remover.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
