.TH man 1 "31 March 2007" "0.1" "uncomment man page"
.SH NAME
uncomment
.SH SYNOPSIS
.B uncomment does removes lines starting with # from given file.
.SH EXAMPLES
uncomment /home/zoup/source/source.pl.
.SH DESCRIPTION
note that this script is just able to remove lines starting with # comment style , not C or PHP .
.SH OPTIONS
uncomment <file path>
.SH FILES
.P 
.I /usr/share/man/man1/uncomment.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
unable to detect any kind of comment but # comments
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
