.TH man 1 "31 March 2007" "0.1" "Bosat man page"
.SH NAME
Bosat
.SH SYNOPSIS
.B Bosat is a Toolkit for system administrators , professional users . 
.SH DESCRIPTION
this is set of tools that allows many tasks to be done in more automated and faster way .
.SH FILES
.P 
.I /usr/share/man/man1/Bosat.1.gz
.nf
.I /usr/share/man/man1/clean_radacct_eol.1.gz
.nf
.I /usr/share/man/man1/clean_radacct_inactive.1.gz
.nf
.I /usr/share/man/man1/find_sgidsuid.1.gz
.nf
.I /usr/share/man/man1/local_domain_generator.1.gz
.nf
.I /usr/share/man/man1/maildir2mbox.1.gz
.nf
.I /usr/share/man/man1/packup.1.gz
.nf
.I /usr/share/man/man1/powersave.1.gz
.nf
.I /usr/share/man/man1/ps_cpu.1.gz
.nf
.I /usr/share/man/man1/ps_mem.1.gz
.nf
.I /usr/share/man/man1/ps_nice.1.gz
.nf
.I /usr/share/man/man1/ps_size.1.gz
.nf
.I /usr/share/man/man1/reniceall.1.gz
.nf
.I /usr/share/man/man1/replace_argument_with_blank_line.1.gz
.nf
.I /usr/share/man/man1/replacer.1.gz
.nf
.I /usr/share/man/man1/runner.1.gz
.nf
.I /usr/share/man/man1/runner_waitfor_return.1.gz
.nf
.I /usr/share/man/man1/space_remover.1.gz
.nf
.I /usr/share/man/man1/swsup.1.gz
.nf
.I /usr/share/man/man1/uncomment.1.gz
.nf
.I /usr/share/man/man1/uptimer.1.gz
.nf
.I /usr/share/man/man1/wait_for.1.gz
.nf
.SH SEE ALSO
.BR bosat (1), 
.BR clean_radacct_eol (1),
.BR clean_radacct_inactive (1),
.BR find_sgidsuid (1),
.BR local_domain_generator (1),
.BR maildir2mbox (1),
.BR packup (1),
.BR powersave (1),
.BR ps_cpu (1),
.BR ps_mem (1),
.BR ps_nice (1),
.BR ps_size (1),
.BR reniceall (1),
.BR replace_argument_with_blank_line (1),
.BR replacer (1),
.BR runner (1),
.BR runner_waitfor_return (1),
.BR space_remover (1),
.BR swsup (1),
.BR uncomment (1),
.BR uptimer (1),
.BR wait_for (1)
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
