.TH man 1 "31 March 2007" "0.1" "ps_mem man page"
.SH NAME
ps_mem
.SH SYNOPSIS
.B Ps_mem does sort processes by mem usage
.SH EXAMPLES
ps_mem
.SH DESCRIPTION
it does sort processes by mem usage
.SH OPTIONS
ps_mem
.SH FILES
.P 
.I /usr/share/man/man1/ps_mem.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
