.TH man 1 "31 March 2007" "0.1" "ps_nice man page"
.SH NAME
ps_nice
.SH SYNOPSIS
.B Ps_nice does sort processes by nice value
.SH EXAMPLES
ps_nice
.SH DESCRIPTION
it does sort processes by nice value
.SH OPTIONS
ps_nice
.SH FILES
.P 
.I /usr/share/man/man1/ps_nice.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
