a.TH man 1 "31 March 2007" "0.1" "ps_size man page"
.SH NAME
ps_size
.SH SYNOPSIS
.B Ps_size does sort processes by process size
.SH EXAMPLES
ps_size /home/*
.SH DESCRIPTION
it does sort processes by process size usage
.SH OPTIONS
ps_size
.SH FILES
.P 
.I /usr/share/man/man1/ps_size.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
