.TH man 1 "31 March 2007" "0.1" "replacer man page"
.SH NAME
replacer
.SH SYNOPSIS
.B this scripts replaces string on multiple files
.SH EXAMPLES
replacer clas class /home/zoup/source/
.SH DESCRIPTION
this script replace given string with correct string .
.SH OPTIONS
replacer <current word> <replacing word> <path>
.SH FILES
.P 
.I /usr/share/man/man1/replacer.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
