.TH man 1 "31 March 2007" "0.1" "replace_argument_with_blank_line man page"
.SH NAME
replace_argument_with_blank_line
.SH SYNOPSIS
.B this scripts remove matching lines on given files.
.SH EXAMPLES
replace_argument_with_blank_line password /home/zoup/report/
.SH DESCRIPTION
this script removes matching lines , suitable for clearing password containing files .
.SH OPTIONS
replace_argument_with_blank_line <word> <path>
.SH FILES
.P 
.I /usr/share/man/man1/replace_argument_with_blank_line.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
