.TH man 1 "31 March 2007" "0.1" "runner man page"
.SH NAME
runner
.SH SYNOPSIS
.B runs given command for given interval.
.SH EXAMPLES
runner "cat /proc/meminfo" 10
.SH DESCRIPTION
runs given command for given interval , its able to run batch commands.
.SH OPTIONS
runner <command> <interval>
.SH FILES
.P 
.I /usr/share/man/man1/runner.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
