.TH man 1 "31 March 2007" "0.1" "swsup man page"
.SH NAME
swsup
.SH SYNOPSIS
.B swsup does suspend to disk on platforms that support it 
.SH EXAMPLES
swsup
.SH DESCRIPTION
note that you need kernel support for this 
.SH OPTIONS
swsup
.SH FILES
.P 
.I /usr/share/man/man1/swsup.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
