#!/bin/bash
#
# Simple Installer
#
if [ $USER='root' ];then
echo "good , you are root"
echo -n "coping Documents to /usr/share/doc/bosat .."
mkdir /usr/share/doc/bosat/ 2>/dev/null
cp LICENSE README /usr/share/doc/bosat/
echo "."

echo -n "fixing scripts and man pages permission .."
chmod -R 755 src
chmod -R 644 man
echo "."

echo -n "gziping man pages .."
gzip man/* 2>/dev/null
echo "."

echo -n "installing man pages .."
cp man/ps_size.1.gz /usr/share/man/man1/
cp man/reporter.1.gz /usr/share/man/man1/
cp man/space_remover.1.gz /usr/share/man/man1/
cp man/uncomment.1.gz /usr/share/man/man1/
cp man/clean_radacct_inactive.1.gz /usr/share/man/man1/
cp man/runner.1.gz /usr/share/man/man1/
cp man/wait_for.1.gz /usr/share/man/man1/
cp man/find_sgidsuid.1.gz /usr/share/man/man1/
cp man/clean_radacct_eol.1.gz /usr/share/man/man1/
cp man/replacer.1.gz /usr/share/man/man1/
cp man/pgen.1.gz /usr/share/man/man1/
cp man/replace_argument_with_blank_line.1.gz /usr/share/man/man1/
cp man/ps_cpu.1.gz /usr/share/man/man1/
cp man/ps_mem.1.gz /usr/share/man/man1/
cp man/maildir2mbox.1.gz /usr/share/man/man1/
cp man/local_domain_generator.1.gz /usr/share/man/man1/
cp man/bosat.1.gz /usr/share/man/man1/
cp man/reniceall.1.gz /usr/share/man/man1/
cp man/runner_waitfor_return.1.gz /usr/share/man/man1/
cp man/packup.1.gz /usr/share/man/man1/
cp man/uptimer.1.gz /usr/share/man/man1/
cp man/powersave.8.gz /usr/share/man/man8/
cp man/swsup.8.gz /usr/share/man/man8/
cp man/open_base_dir_added.1.gz /usr/share/man/man1/
echo "."
echo -n "installing scripts .."
cp src/pgen /usr/bin/
cp src/local_domain_generator /usr/sbin/
cp src/replacer /usr/bin/
cp src/reporter /usr/bin/
cp src/runner_waitfor_return /usr/bin/
cp src/replace_argument_with_blank_line /usr/bin/
cp src/find_sgidsuid /usr/bin/
cp src/wait_for /usr/bin/
cp src/uncomment /usr/bin/
cp src/maildir2mbox /usr/bin/
cp src/clean_radacct_inactive /usr/bin/
cp src/packup /usr/bin/
cp src/ps_cpu /usr/bin/
cp src/ps_mem /usr/bin/
cp src/runner /usr/bin/
cp src/uptimer /usr/bin/
cp src/space_remover /usr/bin/
cp src/clean_radacct_eol /usr/bin/
cp src/reniceall /usr/bin/
cp src/ps_nice /usr/bin/
cp src/ps_size /usr/bin/
cp src/powersave /usr/sbin/
cp src/swsup /usr/sbin/
cp src/open_base_dir_added /usr/sbin
echo "."
echo -n "Fixing permissions .."
chown root:root /usr/share/man/man1/ps_size.1.gz 
chown root:root /usr/share/man/man1/reporter.1.gz 
chown root:root /usr/share/man/man1/space_remover.1.gz 
chown root:root /usr/share/man/man1/uncomment.1.gz 
chown root:root /usr/share/man/man1/clean_radacct_inactive.1.gz 
chown root:root /usr/share/man/man1/runner.1.gz 
chown root:root /usr/share/man/man1/wait_for.1.gz 
chown root:root /usr/share/man/man1/find_sgidsuid.1.gz 
chown root:root /usr/share/man/man1/clean_radacct_eol.1.gz 
chown root:root /usr/share/man/man1/replacer.1.gz 
chown root:root /usr/share/man/man1/pgen.1.gz 
chown root:root /usr/share/man/man1/replace_argument_with_blank_line.1.gz 
chown root:root /usr/share/man/man1/ps_cpu.1.gz 
chown root:root /usr/share/man/man1/ps_mem.1.gz 
chown root:root /usr/share/man/man1/maildir2mbox.1.gz 
chown root:root /usr/share/man/man1/local_domain_generator.1.gz 
chown root:root /usr/share/man/man1/bosat.1.gz 
chown root:root /usr/share/man/man1/packup.1.gz
chown root:root /usr/share/man/man1/uptimer.1.gz
chown root:root /usr/share/man/man1/reniceall.1.gz 
chown root:root /usr/share/man/man1/runner_waitfor_return.1.gz 
chown root:root /usr/share/man/man8/powersave.8.gz 
chown root:root /usr/share/man/man8/swsup.8.gz 
chown root:root /usr/share/man/man1/open_base_dir_added.1.gz
chown root:root /usr/bin/pgen
chown root:root /usr/sbin/local_domain_generator
chown root:root /usr/bin/replacer
chown root:root /usr/bin/reporter
chown root:root /usr/bin/runner_waitfor_return
chown root:root /usr/bin/replace_argument_with_blank_line
chown root:root /usr/bin/find_sgidsuid
chown root:root /usr/bin/wait_for
chown root:root /usr/bin/uncomment
chown root:root /usr/bin/maildir2mbox
chown root:root /usr/bin/clean_radacct_inactive
chown root:root /usr/bin/packup
chown root:root /usr/bin/ps_cpu
chown root:root /usr/bin/ps_mem
chown root:root /usr/bin/runner
chown root:root /usr/bin/uptimer
chown root:root /usr/bin/space_remover
chown root:root /usr/bin/clean_radacct_eol
chown root:root /usr/bin/reniceall
chown root:root /usr/bin/ps_nice
chown root:root /usr/bin/ps_size
chown root:root /usr/sbin/powersave
chown root:root /usr/sbin/swsup
chown root:root /usr/sbin/open_base_dir_added
chmod 644 /usr/share/man/man1/ps_size.1.gz 
chmod 644 /usr/share/man/man1/reporter.1.gz 
chmod 644 /usr/share/man/man1/space_remover.1.gz 
chmod 644 /usr/share/man/man1/uncomment.1.gz 
chmod 644 /usr/share/man/man1/clean_radacct_inactive.1.gz 
chmod 644 /usr/share/man/man1/runner.1.gz 
chmod 644 /usr/share/man/man1/wait_for.1.gz 
chmod 644 /usr/share/man/man1/find_sgidsuid.1.gz 
chmod 644 /usr/share/man/man1/clean_radacct_eol.1.gz 
chmod 644 /usr/share/man/man1/replacer.1.gz 
chmod 644 /usr/share/man/man1/pgen.1.gz 
chmod 644 /usr/share/man/man1/replace_argument_with_blank_line.1.gz 
chmod 644 /usr/share/man/man1/ps_cpu.1.gz 
chmod 644 /usr/share/man/man1/ps_mem.1.gz 
chmod 644 /usr/share/man/man1/maildir2mbox.1.gz 
chmod 644 /usr/share/man/man1/local_domain_generator.1.gz 
chmod 644 /usr/share/man/man1/bosat.1.gz 
chmod 644 /usr/share/man/man1/packup.1.gz
chmod 644 /usr/share/man/man1/uptimer.1.gz
chmod 644 /usr/share/man/man1/reniceall.1.gz 
chmod 644 /usr/share/man/man1/runner_waitfor_return.1.gz 
chmod 644 /usr/share/man/man8/powersave.8.gz 
chmod 644 /usr/share/man/man8/swsup.8.gz 
chmod 644 /usr/share/man/man1/open_base_dir_added.1.gz
chmod 755 /usr/bin/pgen
chmod 755 /usr/sbin/local_domain_generator
chmod 755 /usr/bin/replacer
chmod 755 /usr/bin/reporter
chmod 755 /usr/bin/runner_waitfor_return
chmod 755 /usr/bin/replace_argument_with_blank_line
chmod 755 /usr/bin/find_sgidsuid
chmod 755 /usr/bin/wait_for
chmod 755 /usr/bin/uncomment
chmod 755 /usr/bin/maildir2mbox
chmod 755 /usr/bin/clean_radacct_inactive
chmod 755 /usr/bin/packup
chmod 755 /usr/bin/ps_cpu
chmod 755 /usr/bin/ps_mem
chmod 755 /usr/bin/runner
chmod 755 /usr/bin/uptimer
chmod 755 /usr/bin/space_remover
chmod 755 /usr/bin/clean_radacct_eol
chmod 755 /usr/bin/reniceall
chmod 755 /usr/bin/ps_nice
chmod 755 /usr/bin/ps_size
chmod 755 /usr/sbin/powersave
chmod 755 /usr/sbin/swsup
chmod 755 /usr/sbin/open_base_dir_added
echo "."
echo "Done , read bosat documents starting with bosat (1) man page"
echo "http://bosat.berlios.de"
else 
echo please run as root , note that installing is not really essential .
fi
