#!/usr/bin/perl
#
#
#
# this is renice all script , act like killall for nice 
#
#
#
use warnings;
use strict;

die "DIED : no input , use reniceall <new nice value> <proc name>  \n" unless ($ARGV[0] & $ARGV[1]) ;
my $proc_list=`pidof $ARGV[1]`;
system  ("renice $ARGV[0] $proc_list");
