.TH man 1 "31 March 2007" "0.1" "ps_cpu man page"
.SH NAME
ps_cpu
.SH SYNOPSIS
.B Ps_cpu does sort processes by cpu usage
.SH EXAMPLES
ps_cpu /home/*
.SH DESCRIPTION
it does sort processes by cpu usage
.SH OPTIONS
ps_cpu
.SH FILES
.P 
.I /usr/share/man/man1/ps_cpu.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
