.TH man 1 "31 March 2007" "0.1" "reniceall man page"
.SH NAME
reniceall
.SH SYNOPSIS
.B Reniceall does renice on given process name .
.SH EXAMPLES
reniceall -19 httpd
.SH DESCRIPTION
this is doing the same as killall for kill .
.SH OPTIONS
reniceall <nice value> <process name>
.SH FILES
.P 
.I /usr/share/man/man1/reniceall.1.gz
.SH SEE ALSO
.BR bosat (1), 
.SH BUGS
No known bugs at this time.
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
